Automatically go through ten pages of earnings calls...

https://www.fool.com/earnings-call-transcripts/

https://www.fool.com/earnings-call-transcripts/page/10/

And download the 20 earning calls on each page.

For each earnings call:

- Split the call into parts: prepared remarks, and Q&As
- For each part, identify the speakers and their text (what they say)
- Store it all in two dataframes
  - DF1: [EarningsCallID, CompanyName, CallDate, EarningsCallText] - each row is an entire earnings call
  - DF2: [SpeakerTurnID (unique, sequential), EarningsCallID (never change from DF1),  SpeakerName, PreparedOrQA, Text] - each row is a speaker turn in a call

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from pathlib import Path
import time

In [3]:
foolSite = "https://www.fool.com/earnings-call-transcripts/"

callSites = []
callSites.append(foolSite)

for i in range(9):
  # print(foolSite + "page/" + str(i+2) + "/")
  callSites.append((foolSite + "page/" + str(i+2) + "/"))

print(callSites)

['https://www.fool.com/earnings-call-transcripts/', 'https://www.fool.com/earnings-call-transcripts/page/2/', 'https://www.fool.com/earnings-call-transcripts/page/3/', 'https://www.fool.com/earnings-call-transcripts/page/4/', 'https://www.fool.com/earnings-call-transcripts/page/5/', 'https://www.fool.com/earnings-call-transcripts/page/6/', 'https://www.fool.com/earnings-call-transcripts/page/7/', 'https://www.fool.com/earnings-call-transcripts/page/8/', 'https://www.fool.com/earnings-call-transcripts/page/9/', 'https://www.fool.com/earnings-call-transcripts/page/10/']

In [4]:
url = callSites[0]
response = requests.get(url)
print(response.text[:2000])
content = response.text

<!DOCTYPE html><html lang="en" class="__className_319f37 __variable_c44347"><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/><link rel="preload" as="image" imageSrcSet="https://g.foolcdn.com/misc-assets/logo-tmf-primary-1-magenta-purple-reversed.svg?_w=256 1x, https://g.foolcdn.com/misc-assets/logo-tmf-primary-1-magenta-purple-reversed.svg?_w=320 2x"/><link rel="preload" as="image" imageSrcSet="https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ftmf_holdingco_logo_stacked_magenta_royalpurple_rev.png&amp;w=48&amp;op=resize 1x, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ftmf_holdingco_logo_stacked_magenta_royalpurple_rev.png&amp;w=96&amp;op=resize 2x"/><link rel="stylesheet" href="https://g.foolcdn.com/static/foolcom/_next/static/css/d7011f77077cb8f5.css" data-precedence="next"/><link rel="stylesheet" href="https://g.foolcdn.com/static/foolcom/_next/static/css/02c67f1af3f6ba77.css" data-precedence="next"/><link rel="stylesheet" href="https://g.foolcdn.com/static/foolcom/_next/static/css/dd5d352a082118c1.css" data-precedence="next"/><link rel="stylesheet" href="https://g.foolcdn.com/static/foolcom/_next/static/css/3c638ba177581267.css" data-precedence="next"/><link rel="stylesheet" href="https://g.foolcdn.com/static/foolcom/_next/static/css/0cd54441d5cc9677.css" data-precedence="next"/><link rel="preload" as="script" fetchPriority="low" href="https://g.foolcdn.com/static/foolcom/_next/static/chunks/webpack-024da2c289f091bc.js"/><script src="https://g.foolcdn.com/static/foolcom/_next/static/chunks/4bd1b696-5cd00193ecc7ed4f.js" async=""></script><script src="https://g.foolcdn.com/static/foolcom/_next/static/chunks/9da6db1e-3db5681b4f28ad13.js" async=""></script><script src="https://g.foolcdn.com/static/foolcom/_next/static/chunks/4956-07da604e463740f2.js" async=""></script><script src="https://g.foolcdn.com/static/foolcom/_next/static/chunks/main-app-7b153e0495d0738

In [5]:
soup = BeautifulSoup(content, 'html.parser')
print(soup.find('a', {"class":"text-gray-1100 group hover:no-underline!"}))
print(soup.find_all('a', {"class":"text-gray-1100 group hover:no-underline!"}))
len(soup.find_all('a', {"class":"text-gray-1100 group hover:no-underline!"}))
type(soup.find_all('a', {"class":"text-gray-1100 group hover:no-underline!"}))

<a class="text-gray-1100 group hover:no-underline!" href="/earnings/call-transcripts/2026/10/14/fastenal-fast-q3-2026-earnings-call-transcript/"><h5 class="md:text-h5 text-md mb-[6px] self-center font-medium group-hover:underline md:mb-[4px]">Fastenal (FAST) Q3 2026 Earnings Call Transcript</h5><div class="text-md text-gray-800">Revenue surged 15.5% as large customer wins and digital sales drove market share gains.</div></a>
[<a class="text-gray-1100 group hover:no-underline!" href="/earnings/call-transcripts/2026/10/14/fastenal-fast-q3-2026-earnings-call-transcript/"><h5 class="md:text-h5 text-md mb-[6px] self-center font-medium group-hover:underline md:mb-[4px]">Fastenal (FAST) Q3 2026 Earnings Call Transcript</h5><div class="text-md text-gray-800">Revenue surged 15.5% as large customer wins and digital sales drove market share gains.</div></a>, <a class="text-gray-1100 group hover:no-underline!" href="/earnings/call-transcripts/2026/10/14/blackrock-blk-q3-2026-earnings-call-transcript/"><h5 class="md:text-h5 text-md mb-[6px] self-center font-medium group-hover:underline md:mb-[4px]">BlackRock (BLK) Q3 2026 Earnings Call Transcript</h5><div class="text-md text-gray-800">Record $7.8B revenue and $15.5T AUM as AI infrastructure demand reshapes asset management.</div></a>, <a class="text-gray-1100 group hover:no-underline!" href="/earnings/call-transcripts/2026/10/14/morgan-stanley-ms-q3-2026-earnings-call-transcript/"><h5 class="md:text-h5 text-md mb-[6px] self-center font-medium group-hover:underline md:mb-[4px]">Morgan Stanley (MS) Q3 2026 Earnings Call Transcript</h5><div class="text-md text-gray-800">Record wealth assets hit $10.5 trillion as equities revenue surged 41% year over year.</div></a>, <a class="text-gray-1100 group hover:no-underline!" href="/earnings/call-transcripts/2026/10/14/sono-tek-sotk-q2-2027-earnings-call-transcript/"><h5 class="md:text-h5 text-md mb-[6px] self-center font-medium group-hover:underline md:mb-[4px]">Sono-Tek (SOTK) Q2 2027 Earnings Call Transcript</h5><div class="text-md text-gray-800">Medical market sales surged 289% as customers shifted to commercial manufacturing.</div></a>, <a class="text-gray-1100 group hover:no-underline!" href="/earnings/call-transcripts/2026/10/14/asml-asml-q3-2026-earnings-call-transcript/"><h5 class="md:text-h5 text-md mb-[6px] self-center font-medium group-hover:underline md:mb-[4px]">ASML (ASML) Q3 2026 Earnings Call Transcript</h5><div class="text-md text-gray-800">Record €11.7B quarterly sales and €5.0B net income signal robust AI infrastructure demand.</div></a>, <a class="text-gray-1100 group hover:no-underline!" href="/earnings/call-transcripts/2026/10/14/azz-azz-q2-2027-earnings-call-transcript/"><h5 class="md:text-h5 text-md mb-[6px] self-center font-medium group-hover:underline md:mb-[4px]">AZZ (AZZ) Q2 2027 Earnings Call Transcript</h5><div class="text-md text-gray-800">Industrial and infrastructure demand propels record sales; management raises full-year guidance.</div></a>, <a class="text-gray-1100 group hover:no-underline!" href="/earnings/call-transcripts/2026/10/14/bofa-bac-q3-2026-earnings-call-transcript/"><h5 class="md:text-h5 text-md mb-[6px] self-center font-medium group-hover:underline md:mb-[4px]">BofA (BAC) Q3 2026 Earnings Call Transcript</h5><div class="text-md text-gray-800">Consumer banking and wealth management offset trading headwinds and regulatory charges.</div></a>, <a class="text-gray-1100 group hover:no-underline!" href="/earnings/call-transcripts/2026/10/14/wells-fargo-wfc-q3-2026-earnings-call-transcript/"><h5 class="md:text-h5 text-md mb-[6px] self-center font-medium group-hover:underline md:mb-[4px]">Wells Fargo (WFC) Q3 2026 Earnings Call Transcript</h5><div class="text-md text-gray-800">Scharf highlights AI scale advantages as bank deploys tokenized deposits.</div></a>, <a class="text-gray-1100 group hover:no-underline!" href="/earnings/call-transcripts/2026/10/13/fb-financial-fbk-q3-2026-earnings-call-transcript/"><h5 class="md:text-h5 text-md mb-[6px] self-center font-medium group-hover:underline md:mb-[4px]">FB Financial (FBK) Q3 2026 Earnings Call Transcript</h5><div class="text-md text-gray-800">Net income hit $60.2 million amid loan growth, but mortgage banking faced headwinds.</div></a>, <a class="text-gray-1100 group hover:no-underline!" href="/earnings/call-transcripts/2026/10/13/jj-jnj-q3-2026-earnings-call-transcript/"><h5 class="md:text-h5 text-md mb-[6px] self-center font-medium group-hover:underline md:mb-[4px]">J&amp;J (JNJ) Q3 2026 Earnings Call Transcript</h5><div class="text-md text-gray-800">Innovative Medicine drove 7.9% growth as revenue hit $25.4 billion.</div></a>, <a class="text-gray-1100 group hover:no-underline!" href="/earnings/call-transcripts/2026/10/13/albertsons-aci-q2-2026-earnings-call-transcript/"><h5 class="md:text-h5 text-md mb-[6px] self-center font-medium group-hover:underline md:mb-[4px]">Albertsons (ACI) Q2 2026 Earnings Call Transcript</h5><div class="text-md text-gray-800">CEO Morris warns traffic and units lag as retailer launches turnaround strategy.</div></a>, <a class="text-gray-1100 group hover:no-underline!" href="/earnings/call-transcripts/2026/10/13/unitedhealth-unh-q3-2026-earnings-call-transcript/"><h5 class="md:text-h5 text-md mb-[6px] self-center font-medium group-hover:underline md:mb-[4px]">UnitedHealth (UNH) Q3 2026 Earnings Call Transcript</h5><div class="text-md text-gray-800">Medical care ratio improved to 88.4% as AI initiatives reduce administrative friction.</div></a>, <a class="text-gray-1100 group hover:no-underline!" href="/earnings/call-transcripts/2026/10/13/citi-c-q3-2026-earnings-call-transcript/"><h5 class="md:text-h5 text-md mb-[6px] self-center font-medium group-hover:underline md:mb-[4px]">Citi (C) Q3 2026 Earnings Call Transcript</h5><div class="text-md text-gray-800">Citigroup posts best Q3 revenue in a decade, net income surges 40% YoY.</div></a>, <a class="text-gray-1100 group hover:no-underline!" href="/earnings/call-transcripts/2026/10/13/goldman-sachs-gs-q3-2026-earnings-call-transcript/"><h5 class="md:text-h5 text-md mb-[6px] self-center font-medium group-hover:underline md:mb-[4px]">Goldman Sachs (GS) Q3 2026 Earnings Call Transcript</h5><div class="text-md text-gray-800">Record equities financing and $4.1T assets under supervision discussed.</div></a>, <a class="text-gray-1100 group hover:no-underline!" href="/earnings/call-transcripts/2026/10/13/dominos-dpz-q3-2026-earnings-call-transcript/"><h5 class="md:text-h5 text-md mb-[6px] self-center font-medium group-hover:underline md:mb-[4px]">Domino's (DPZ) Q3 2026 Earnings Call Transcript</h5><div class="text-md text-gray-800">Leadership transition underway as Domino's faces consumer spending pressures.</div></a>, <a class="text-gray-1100 group hover:no-underline!" href="/earnings/call-transcripts/2026/10/13/jpmorgan-chase-jpm-q3-2026-earnings-call-transcript/"><h5 class="md:text-h5 text-md mb-[6px] self-center font-medium group-hover:underline md:mb-[4px]">JPMorgan Chase (JPM) Q3 2026 Earnings Call Transcript</h5><div class="text-md text-gray-800">Net income surged 6% to $15.3 billion as investment banking and markets revenue accelerated.</div></a>, <a class="text-gray-1100 group hover:no-underline!" href="/earnings/call-transcripts/2026/10/13/leifras-lfs-q2-2026-earnings-call-transcript/"><h5 class="md:text-h5 text-md mb-[6px] self-center font-medium group-hover:underline md:mb-[4px]">Leifras (LFS) Q2 2026 Earnings Call Transcript</h5><div class="text-md text-gray-800">Net income surged 43.5% as Sports School and Social segments both accelerated.</div></a>, <a class="text-gray-1100 group hover:no-underline!" href="/earnings/call-transcripts/2026/10/09/delta-dal-q3-2026-earnings-call-transcript/"><h5 class="md:text-h5 text-md mb-[6px] self-center font-medium group-hover:underline md:mb-[4px]">Delta (DAL) Q3 2026 Earnings Call Transcript</h5><div class="text-md text-gray-800">Revenue surged 16% on strong travel demand, but fuel costs climbed $500M above guidance.</div></a>, <a class="text-gray-1100 group hover:no-underline!" href="/earnings/call-transcripts/2026/10/09/new-horizon-aircraft-hovr-q1-2027-earnings-call-transcript/"><h5 class="md:text-h5 text-md mb-[6px] self-center font-medium group-hover:underline md:mb-[4px]">New Horizon Aircraft (HOVR) Q1 2027 Earnings Call Transcript</h5><div class="text-md text-gray-800">Hybrid-electric demonstrator nears completion as cash runway extends to 24 months.</div></a>, <a class="text-gray-1100 group hover:no-underline!" href="/earnings/call-transcripts/2026/10/09/oil-dri-odc-q4-2026-earnings-call-transcript/"><h5 class="md:text-h5 text-md mb-[6px] self-center font-medium group-hover:underline md:mb-[4px]">Oil-Dri (ODC) Q4 2026 Earnings Call Transcript</h5><div class="text-md text-gray-800">Record net income and cash flow highlight strong execution despite margin pressures.</div></a>]

bs4.element.ResultSet

In [6]:
atag = soup.find('a', {"class":"text-gray-1100 group hover:no-underline!"})
atags = soup.find_all('a', {"class":"text-gray-1100 group hover:no-underline!"})
print(atag.attrs)
print(atag.attrs['href'])
print("https://www.fool.com" + atag.attrs['href'])
print(atags[0].attrs['href'])

{'class': ['text-gray-1100', 'group', 'hover:no-underline!'], 'href': '/earnings/call-transcripts/2026/10/14/fastenal-fast-q3-2026-earnings-call-transcript/'}
/earnings/call-transcripts/2026/10/14/fastenal-fast-q3-2026-earnings-call-transcript/
https://www.fool.com/earnings/call-transcripts/2026/10/14/fastenal-fast-q3-2026-earnings-call-transcript/
/earnings/call-transcripts/2026/10/14/fastenal-fast-q3-2026-earnings-call-transcript/

In [7]:
for i in atags:
  call = "https://www.fool.com" + i.attrs['href']
  response = requests.get(call)
  print(response.text[:2000])

<!DOCTYPE html><html lang="en" class="__className_319f37 __variable_c44347"><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/><link rel="preload" as="image" imageSrcSet="https://g.foolcdn.com/misc-assets/logo-tmf-primary-1-magenta-purple-reversed.svg?_w=256 1x, https://g.foolcdn.com/misc-assets/logo-tmf-primary-1-magenta-purple-reversed.svg?_w=320 2x"/><link rel="preload" as="image" imageSrcSet="https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ftmf_holdingco_logo_stacked_magenta_royalpurple_rev.png&amp;w=48&amp;op=resize 1x, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ftmf_holdingco_logo_stacked_magenta_royalpurple_rev.png&amp;w=96&amp;op=resize 2x"/><link rel="preload" as="image" href="https://g.foolcdn.com/misc-assets/foolcom-sidebar-small-icon.png"/><link rel="preload" as="image" imageSrcSet="https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=320&amp;op=resize 320w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=384&amp;op=resize 384w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=640&amp;op=resize 640w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=750&amp;op=resize 750w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=828&amp;op=resize 828w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=1080&amp;op=resize 1080w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=1200&amp;op=resize 1200w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=1920&amp;op=resize 1920w, https://g.foolcd
<!DOCTYPE html><html lang="en" class="__className_319f37 __variable_c44347"><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/><link rel="preload" as="image" imageSrcSet="https://g.foolcdn.com/misc-assets/logo-tmf-primary-1-magenta-purple-reversed.svg?_w=256 1x, https://g.foolcdn.com/misc-assets/logo-tmf-primary-1-magenta-purple-reversed.svg?_w=320 2x"/><link rel="preload" as="image" imageSrcSet="https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ftmf_holdingco_logo_stacked_magenta_royalpurple_rev.png&amp;w=48&amp;op=resize 1x, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ftmf_holdingco_logo_stacked_magenta_royalpurple_rev.png&amp;w=96&amp;op=resize 2x"/><link rel="preload" as="image" href="https://g.foolcdn.com/misc-assets/foolcom-sidebar-small-icon.png"/><link rel="preload" as="image" imageSrcSet="https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=320&amp;op=resize 320w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=384&amp;op=resize 384w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=640&amp;op=resize 640w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=750&amp;op=resize 750w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=828&amp;op=resize 828w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=1080&amp;op=resize 1080w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=1200&amp;op=resize 1200w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=1920&amp;op=resize 1920w, https://g.foolcd
<!DOCTYPE html><html lang="en" class="__className_319f37 __variable_c44347"><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/><link rel="preload" as="image" imageSrcSet="https://g.foolcdn.com/misc-assets/logo-tmf-primary-1-magenta-purple-reversed.svg?_w=256 1x, https://g.foolcdn.com/misc-assets/logo-tmf-primary-1-magenta-purple-reversed.svg?_w=320 2x"/><link rel="preload" as="image" imageSrcSet="https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ftmf_holdingco_logo_stacked_magenta_royalpurple_rev.png&amp;w=48&amp;op=resize 1x, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ftmf_holdingco_logo_stacked_magenta_royalpurple_rev.png&amp;w=96&amp;op=resize 2x"/><link rel="preload" as="image" href="https://g.foolcdn.com/misc-assets/foolcom-sidebar-small-icon.png"/><link rel="preload" as="image" imageSrcSet="https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=320&amp;op=resize 320w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=384&amp;op=resize 384w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=640&amp;op=resize 640w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=750&amp;op=resize 750w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=828&amp;op=resize 828w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=1080&amp;op=resize 1080w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=1200&amp;op=resize 1200w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=1920&amp;op=resize 1920w, https://g.foolcd
<!DOCTYPE html><html lang="en" class="__className_319f37 __variable_c44347"><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/><link rel="preload" as="image" imageSrcSet="https://g.foolcdn.com/misc-assets/logo-tmf-primary-1-magenta-purple-reversed.svg?_w=256 1x, https://g.foolcdn.com/misc-assets/logo-tmf-primary-1-magenta-purple-reversed.svg?_w=320 2x"/><link rel="preload" as="image" imageSrcSet="https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ftmf_holdingco_logo_stacked_magenta_royalpurple_rev.png&amp;w=48&amp;op=resize 1x, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ftmf_holdingco_logo_stacked_magenta_royalpurple_rev.png&amp;w=96&amp;op=resize 2x"/><link rel="preload" as="image" href="https://g.foolcdn.com/misc-assets/foolcom-sidebar-small-icon.png"/><link rel="preload" as="image" imageSrcSet="https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=320&amp;op=resize 320w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=384&amp;op=resize 384w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=640&amp;op=resize 640w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=750&amp;op=resize 750w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=828&amp;op=resize 828w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=1080&amp;op=resize 1080w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=1200&amp;op=resize 1200w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=1920&amp;op=resize 1920w, https://g.foolcd
<!DOCTYPE html><html lang="en" class="__className_319f37 __variable_c44347"><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/><link rel="preload" as="image" imageSrcSet="https://g.foolcdn.com/misc-assets/logo-tmf-primary-1-magenta-purple-reversed.svg?_w=256 1x, https://g.foolcdn.com/misc-assets/logo-tmf-primary-1-magenta-purple-reversed.svg?_w=320 2x"/><link rel="preload" as="image" imageSrcSet="https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ftmf_holdingco_logo_stacked_magenta_royalpurple_rev.png&amp;w=48&amp;op=resize 1x, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ftmf_holdingco_logo_stacked_magenta_royalpurple_rev.png&amp;w=96&amp;op=resize 2x"/><link rel="preload" as="image" href="https://g.foolcdn.com/misc-assets/foolcom-sidebar-small-icon.png"/><link rel="preload" as="image" imageSrcSet="https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=320&amp;op=resize 320w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=384&amp;op=resize 384w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=640&amp;op=resize 640w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=750&amp;op=resize 750w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=828&amp;op=resize 828w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=1080&amp;op=resize 1080w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=1200&amp;op=resize 1200w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=1920&amp;op=resize 1920w, https://g.foolcd
<!DOCTYPE html><html lang="en" class="__className_319f37 __variable_c44347"><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/><link rel="preload" as="image" imageSrcSet="https://g.foolcdn.com/misc-assets/logo-tmf-primary-1-magenta-purple-reversed.svg?_w=256 1x, https://g.foolcdn.com/misc-assets/logo-tmf-primary-1-magenta-purple-reversed.svg?_w=320 2x"/><link rel="preload" as="image" imageSrcSet="https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ftmf_holdingco_logo_stacked_magenta_royalpurple_rev.png&amp;w=48&amp;op=resize 1x, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ftmf_holdingco_logo_stacked_magenta_royalpurple_rev.png&amp;w=96&amp;op=resize 2x"/><link rel="preload" as="image" href="https://g.foolcdn.com/misc-assets/foolcom-sidebar-small-icon.png"/><link rel="preload" as="image" imageSrcSet="https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=320&amp;op=resize 320w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=384&amp;op=resize 384w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=640&amp;op=resize 640w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=750&amp;op=resize 750w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=828&amp;op=resize 828w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=1080&amp;op=resize 1080w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=1200&amp;op=resize 1200w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=1920&amp;op=resize 1920w, https://g.foolcd
<!DOCTYPE html><html lang="en" class="__className_319f37 __variable_c44347"><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/><link rel="preload" as="image" imageSrcSet="https://g.foolcdn.com/misc-assets/logo-tmf-primary-1-magenta-purple-reversed.svg?_w=256 1x, https://g.foolcdn.com/misc-assets/logo-tmf-primary-1-magenta-purple-reversed.svg?_w=320 2x"/><link rel="preload" as="image" imageSrcSet="https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ftmf_holdingco_logo_stacked_magenta_royalpurple_rev.png&amp;w=48&amp;op=resize 1x, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ftmf_holdingco_logo_stacked_magenta_royalpurple_rev.png&amp;w=96&amp;op=resize 2x"/><link rel="preload" as="image" href="https://g.foolcdn.com/misc-assets/foolcom-sidebar-small-icon.png"/><link rel="preload" as="image" imageSrcSet="https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=320&amp;op=resize 320w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=384&amp;op=resize 384w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=640&amp;op=resize 640w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=750&amp;op=resize 750w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=828&amp;op=resize 828w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=1080&amp;op=resize 1080w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=1200&amp;op=resize 1200w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=1920&amp;op=resize 1920w, https://g.foolcd
<!DOCTYPE html><html lang="en" class="__className_319f37 __variable_c44347"><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/><link rel="preload" as="image" imageSrcSet="https://g.foolcdn.com/misc-assets/logo-tmf-primary-1-magenta-purple-reversed.svg?_w=256 1x, https://g.foolcdn.com/misc-assets/logo-tmf-primary-1-magenta-purple-reversed.svg?_w=320 2x"/><link rel="preload" as="image" imageSrcSet="https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ftmf_holdingco_logo_stacked_magenta_royalpurple_rev.png&amp;w=48&amp;op=resize 1x, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ftmf_holdingco_logo_stacked_magenta_royalpurple_rev.png&amp;w=96&amp;op=resize 2x"/><link rel="preload" as="image" href="https://g.foolcdn.com/misc-assets/foolcom-sidebar-small-icon.png"/><link rel="preload" as="image" imageSrcSet="https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=320&amp;op=resize 320w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=384&amp;op=resize 384w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=640&amp;op=resize 640w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=750&amp;op=resize 750w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=828&amp;op=resize 828w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=1080&amp;op=resize 1080w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=1200&amp;op=resize 1200w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=1920&amp;op=resize 1920w, https://g.foolcd
<!DOCTYPE html><html lang="en" class="__className_319f37 __variable_c44347"><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/><link rel="preload" as="image" imageSrcSet="https://g.foolcdn.com/misc-assets/logo-tmf-primary-1-magenta-purple-reversed.svg?_w=256 1x, https://g.foolcdn.com/misc-assets/logo-tmf-primary-1-magenta-purple-reversed.svg?_w=320 2x"/><link rel="preload" as="image" imageSrcSet="https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ftmf_holdingco_logo_stacked_magenta_royalpurple_rev.png&amp;w=48&amp;op=resize 1x, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ftmf_holdingco_logo_stacked_magenta_royalpurple_rev.png&amp;w=96&amp;op=resize 2x"/><link rel="preload" as="image" href="https://g.foolcdn.com/misc-assets/foolcom-sidebar-small-icon.png"/><link rel="preload" as="image" imageSrcSet="https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=320&amp;op=resize 320w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=384&amp;op=resize 384w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=640&amp;op=resize 640w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=750&amp;op=resize 750w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=828&amp;op=resize 828w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=1080&amp;op=resize 1080w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=1200&amp;op=resize 1200w, https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets%2Ffool-transcripts-logo.png&amp;w=1920&amp;op=resize 1920w, https://g.foolcd

# Downloading 1-200 calls

In [8]:
downloadDir = Path("/content/drive/MyDrive/Fall2026TextMining_me/earnings_calls")
downloadDir.mkdir(parents=True, exist_ok=True)

In [9]:
# collect 200 call links from pages 1-10
callURLs = []

for page in range(1, 11):
  if page == 1:
    url = "https://www.fool.com/earnings-call-transcripts/"
  else:
    url = ("https://www.fool.com/earnings-call-transcripts/page/" + str(page) + "/")

  response = requests.get(url, timeout=30)
  response.raise_for_status()
  soup = BeautifulSoup(response.text, "html.parser")

  atags = soup.find_all("a", {"class": "text-gray-1100 group hover:no-underline!"})

  for a in atags:
    callURLs.append("https://www.fool.com" + a["href"])

  print("Page", page, ":", len(atags), "calls")
  time.sleep(1)

Page 1 : 20 calls
Page 2 : 20 calls
Page 3 : 20 calls
Page 4 : 20 calls
Page 5 : 20 calls
Page 6 : 20 calls
Page 7 : 20 calls
Page 8 : 20 calls
Page 9 : 20 calls
Page 10 : 20 calls

In [10]:
print(len(callURLs)) # check if 200 call links
print(len(set(callURLs))) # check if any call links are duplicated

200
200

In [13]:
# Download each call and organize rows.
callRows = []
speakerRows = []
needsReview = []

for callID, url in enumerate(callURLs, start=1):
  response = requests.get(url, timeout=30)
  response.raise_for_status()
  soup = BeautifulSoup(response.text, "html.parser")

  title = soup.find("h1").get_text(" ", strip=True)
  companyName = title.split(" (")[0]

  dateHeading = soup.find(id="date")
  dateText = dateHeading.find_next_sibling("p").get_text(" ", strip=True)
  callDate = pd.to_datetime(dateText).date().isoformat()

  transcriptHeading = soup.find(id="full-conference-call-transcript")
  paragraphs = transcriptHeading.find_next_siblings("p")

  paragraphTexts = []

  for p in paragraphs:
    paragraphTexts.append(p.get_text(" ", strip=True))

  callText = "\n\n".join(paragraphTexts)

  callRows.append({
    "EarningsCallID": callID,
    "CompanyName": companyName,
    "CallDate": callDate,
    "EarningsCallText": callText,
  })

  # Save the entire transcript as a text file.
  (downloadDir / f"call_{callID}.txt").write_text(callText, encoding="utf-8")

  section = "Prepared"
  currentTurn = None

  for p in paragraphs:
    text = p.get_text(" ", strip=True)
    bold = p.find("strong")

    if not text:
      continue

    # A bold label ending with ":" introduces a speaker.
    if bold and bold.get_text(strip=True).endswith(":"):
      label = bold.get_text(" ", strip=True)
      speakerName = label.rstrip(":").strip()
      speech = text[len(label):].strip()

      # Switch to Q&A when the operator introduces the first question.
      if (
        speakerName.lower() == "operator"
        and "first question" in speech.lower()
      ):
        section = "QA"

      # Every speaker label starts a new turn.
      currentTurn = {
        "SpeakerTurnID": len(speakerRows) + 1,
        "EarningsCallID": callID,
        "SpeakerName": speakerName,
        "PreparedOrQA": section,
        "Text": speech,
      }
      speakerRows.append(currentTurn)

    elif currentTurn is not None:
      # Continue the same speaker's turn across paragraphs.
      currentTurn["Text"] += "\n\n" + text

    else:
      raise ValueError(f"Missing initial speaker label: {url}")

  # Flag calls where the Q&A transition was not detected.
  if section != "QA":
    needsReview.append((callID, url))

  print(callID, companyName, callDate)
  time.sleep(1)

1 Fastenal 2026-10-14
2 BlackRock 2026-10-14
3 Morgan Stanley 2026-10-14
4 Sono-Tek 2026-10-14
5 ASML 2026-10-14
6 AZZ 2026-10-14
7 BofA 2026-10-14
8 Wells Fargo 2026-10-13
9 FB Financial 2026-10-13
10 J&J 2026-10-13
11 Albertsons 2026-10-13
12 UnitedHealth 2026-10-13
13 Citi 2026-10-13
14 Goldman Sachs 2026-10-13
15 Domino's 2026-10-13
16 JPMorgan Chase 2026-10-13
17 Leifras 2026-10-08
18 Delta 2026-10-09
19 New Horizon Aircraft 2026-10-09
20 Oil-Dri 2026-10-09
21 Helen of Troy 2026-10-08
22 Park Aerospace 2026-10-08
23 NovaGold 2026-10-08
24 Byrna 2026-10-08
25 Tilray 2026-10-08
26 PepsiCo 2026-10-08
27 AngioDynamics 2026-10-08
28 Richardson Electronics 2026-10-08
29 Levi Strauss 2026-10-07
30 RGP 2026-10-07
31 Applied Digital 2026-10-07
32 Constellation Brands 2026-10-07
33 Worthington Steel 2026-10-07
34 Saratoga Investment 2026-10-07
35 Neogen 2026-10-06
36 Penguin Solutions 2026-10-06
37 RPM 2026-10-06
38 Lamb Weston 2026-10-06
39 Apogee 2026-10-06
40 Yiren Digital 2026-09-30
41 Nike 2026-10-01
42 McCormick 2026-10-01
43 Accenture 2026-10-01
44 Acuity 2026-10-01
45 Bassett Furniture 2026-10-01
46 Conagra 2026-09-30
47 Progress 2026-09-30
48 Micron 2026-09-30
49 FactSet 2026-09-30
50 Jabil 2026-09-30
51 Cal-Maine Foods 2026-09-30
52 AAR 2026-09-29
53 Moving iMage 2026-09-28
54 CarMax 2026-09-29
55 Uranium Energy 2026-09-29
56 Concentrix 2026-09-29
57 Carnival 2026-09-29
58 Inventiva 2026-09-28
59 Legacy Education 2026-09-24
60 Scholastic 2026-09-24
61 Costco 2026-09-24
62 Precision Optics 2026-09-28
63 Palatin 2026-09-28
64 NetSol 2026-09-28
65 ReposiTrak 2026-09-28
66 Vail Resorts 2026-09-28
67 IDT 2026-09-28
68 Addex 2026-09-28
69 TD SYNNEX 2026-09-24
70 Uxin 2026-09-24
71 BlackBerry 2026-09-24
72 Darden 2026-09-24
73 Fuller 2026-09-24
74 AtlasClear 2026-09-24
75 NeoVolta 2026-09-23
76 Stitch Fix 2026-09-23
77 Paychex 2026-09-23
78 Cintas 2026-09-23
79 General Mills 2026-09-23
80 Cracker Barrel 2026-09-23
81 Worthington 2026-09-23
82 KB Home 2026-09-22
83 Here 2026-09-22
84 MLKN Q1 2027 Earnings Call Transcript 2026-09-22
85 AutoZone 2026-09-22

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Thursday, Sept. 17, 2026 at 5:30 p.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

86 Upexi 2026-09-17

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Thursday, Sept. 17, 2026, at 8 a.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

87 Innate Pharma 2026-09-17

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Thursday, Sept. 17, 2026 at 11 a.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

88 Lennar 2026-09-17

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Tuesday, Sept. 15, 2026 at 11:30 a.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

89 High Tide 2026-09-15

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Wednesday, Sept. 16, 2026 at 5:00 p.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

90 Aeluma 2026-09-16

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Wednesday, Sept. 16, 2026 at 8:00 a.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

91 Luxe 2026-09-16
92 Ispire 2026-09-16

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Wednesday, Sept. 16, 2026 at 11 a.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

93 Evolution Petroleum 2026-09-16

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Tuesday, Sept. 15, 2026 at 11:00 a.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

94 Forgent Power Solutions 2026-09-15

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Tuesday, Sept. 15, 2026 at 8:30 a.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

95 Vera Bradley 2026-09-15

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Tuesday, Sept. 15, 2026 at 8:00 a.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

96 51Talk 2026-09-15

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Friday, Sept. 11, 2026 at 8:30 a.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

97 Rent the Runway 2026-09-11

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Monday, Sept. 14, 2026 at 4:30 p.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

98 ABAT Q4 2026 Earnings Call Transcript 2026-09-14
99 Bioceres 2026-09-15

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Monday, Sept. 14, 2026, at 5 p.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

100 MindWalk 2026-09-14

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Monday, Sept. 14, 2026 at 5:00 p.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

101 Dave & Buster's 2026-09-14
102 Radiant Logistics 2026-09-14
103 Kestra 2026-09-14

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Monday, Sept. 14, 2026 at 8:00 a.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

104 Hain Celestial 2026-09-14

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Monday, Sept. 14, 2026 at 8:30 a.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

105 RF Industries 2026-09-14

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Monday, Sept. 14, 2026 at 10:00 a.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

106 Coda Octopus 2026-09-14
107 CoinShares 2026-09-14

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Friday, September 11, 2026 at 8 a.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

108 Kroger 2026-09-11

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Friday, Sept. 11, 2026 at 9:00 a.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()
/tmp/ipykernel_2276/904308454.py:16: UserWarning: Parsing dates in %A, Sept. %d, %Y at %m:%M a.m. ET format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  callDate = pd.to_datetime(dateText).date().isoformat()

109 Hooker Furnishings 2026-09-11

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Friday, Sept. 11, 2026 at 8:00 a.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

110 MoneyHero 2026-09-11

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Thursday, Sept. 10, 2026, at 5:30 p.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

111 Copart 2026-09-10

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Thursday, Sept. 10, 2026 at 5:00 p.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

112 Zumiez 2026-09-10

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Thursday, Sept. 10, 2026 at 5:30 p.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

113 Descartes 2026-09-10
114 LightPath 2026-09-10

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Thursday, Sept. 10, 2026 at 5 p.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

115 Adobe 2026-09-10

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Thursday, Sept. 10, 2026 at 4:30 p.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

116 Champions Oncology 2026-09-10
117 Frequency Electronics 2026-09-10
118 Oracle 2026-09-10
119 RH 2026-09-10

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Thursday, Sept. 10, 2026 at 9:00 a.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

120 Shoe Station 2026-09-10

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Thursday, Sept. 10, 2026 at 8:30 a.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

121 MasterCraft 2026-09-10

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Thursday, Sept. 10, 2026 at 8 a.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

122 1-800-FLOWERS 2026-09-10
123 Designer Brands 2026-09-10

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Thursday, Sept. 10, 2026 at 8:00 a.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

124 Yuanbao 2026-09-10
125 Vince 2026-09-10
126 IBEX 2026-09-10
127 Lovesac 2026-09-10
128 Macy's 2026-09-10

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Thursday, Sept. 10, 2026 at 10:00 a.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

129 Tsakos Energy Navigation 2026-09-10
130 Alliance Entertainment 2026-09-10

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Wednesday, Sept. 9, 2026, at 4:30 p.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

131 Limoneira 2026-09-09
132 Lesaka 2026-09-10
133 Culp 2026-09-10

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Wednesday, September 9, 2026 at 5:00 p.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

134 Cooper 2026-09-09

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Sept. 9, 2026 at 4:30 p.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

135 AeroVironment 2026-09-09

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Wednesday, Sept. 9, 2026 at 5 p.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

136 Gloo 2026-09-09

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Wednesday, Sept. 9, 2026 at 5:00 p.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

137 Navan 2026-09-09
138 Wealthfront 2026-09-09

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Wednesday, Sept. 9, 2026 at 4:30 p.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

139 American Eagle 2026-09-09
140 Lakeland 2026-09-09
141 RSSS Q4 2026 Earnings Call Transcript 2026-09-09
142 Academy Sports 2026-09-10
143 Skillsoft 2026-09-09

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Wednesday, Sept. 9, 2026 at 8:30 a.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

144 Cognyte 2026-09-09
145 Oddity Tech 2026-09-09

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Wednesday, Sept. 9, 2026 at 8:00 a.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

146 J.Jill 2026-09-09
147 Perma-Pipe 2026-09-09
148 Nano-X Imaging 2026-09-09

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Wednesday, Sept. 9, 2026 at 10:00 a.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

149 Caleres 2026-09-09
150 Core & Main 2026-09-09

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Wednesday, Sept. 9, 2026 at 12 p.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

151 Korn Ferry 2026-09-09
152 Signet 2026-09-09
153 Sunbelt Rentals 2026-09-09

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Wednesday, Sept. 9, 2026 at 9:00 a.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

154 Destination XL 2026-09-09
155 SailPoint 2026-09-09
156 Chewy 2026-09-09

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Wednesday, Sept. 9, 2026 at 11 a.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

157 Optical Cable 2026-09-09

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Wednesday, Sept. 2, 2026, at 5 p.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

158 Netskope 2026-09-02

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Tuesday, Sept. 8, 2026 at 8:00 a.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

159 Canaan 2026-09-08
160 Gamehaus 2026-09-08

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Tuesday, Sept. 8, 2026 at 4:30 p.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

161 Braze 2026-09-08

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Tuesday, Sept. 8, 2026 at 5:00 p.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

162 InnovAge 2026-09-08
163 Casey's 2026-09-09

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Sept. 8, 2026 at 5 p.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

164 Mission Produce 2026-09-08

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Tuesday, Sept. 8, 2026 at 8:30 a.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

165 ABM 2026-09-08
166 UNFI 2026-09-08

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Tuesday, Sept. 8, 2026 at 9:00 p.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()
/tmp/ipykernel_2276/904308454.py:16: UserWarning: Parsing dates in %A, Sept. %d, %Y at %m:%M p.m. ET format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  callDate = pd.to_datetime(dateText).date().isoformat()

167 17 Education 2026-09-08

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Tuesday, Sept. 8, 2026 at 5 p.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

168 ServiceTitan 2026-09-08
169 MIND 2026-09-09

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Thursday, Sept. 3, 2026 at 9:00 a.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

170 VersaBank 2026-09-03

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Friday, Sept. 4, 2026 at 8:30 a.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

171 U.S. Global Investors 2026-09-04

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Thursday, Sept. 3, 2026 at 10:00 a.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

172 Wiley 2026-09-03

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Thursday, Sept. 3, 2026 at 4:30 p.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

173 Mama's Creations 2026-09-03

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Thursday, Sept. 3, 2026 at 8:30 a.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

174 Brady 2026-09-03
175 Torrid 2026-09-03

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Thursday, Sept. 3, 2026 at 8:00 a.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

176 Zegna 2026-09-03

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Thursday, Sept. 3, 2026 at 9 a.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()
/tmp/ipykernel_2276/904308454.py:16: UserWarning: Parsing dates in %A, Sept. %d, %Y at %m a.m. ET format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  callDate = pd.to_datetime(dateText).date().isoformat()

177 BRP 2026-09-03

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Friday, Sept. 4, 2026 at 9:30 a.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

178 KNOT 2026-09-04
179 Oxford Industries 2026-09-03

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Thursday, Sept. 3, 2026 at 5:00 p.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

180 eGain 2026-09-03
181 Lands' End 2026-09-03
182 Concrete Pumping 2026-09-03
183 Smith & Wesson 2026-09-03
184 DocuSign 2026-09-03
185 VS&Co 2026-09-03

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Thursday, Sept. 3, 2026 at 7:00 a.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

186 Hello Group 2026-09-03

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Friday, Sept. 4, 2026, at 11:00 a.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

187 Quanex 2026-09-04
188 Genesco 2026-09-03
189 Planet Labs 2026-09-03
190 Asana 2026-09-03
191 Guidewire 2026-09-03

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Thursday, Sept. 3, 2026 at 11 a.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

192 Toro 2026-09-03
193 Ambarella 2026-09-03
194 Lululemon 2026-09-03
195 Amber 2026-09-03
196 Ciena 2026-09-03

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Thursday, Sept. 3, 2026 at 9:30 a.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

197 Duluth Holdings 2026-09-03
198 UiPath 2026-09-03

/tmp/ipykernel_2276/904308454.py:16: FutureWarning: Parsed string "Thursday, Sept. 3, 2026 at 5 p.m. ET" included an un-recognized timezone "ET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  callDate = pd.to_datetime(dateText).date().isoformat()

199 American Outdoor Brands 2026-09-03
200 Zscaler 2026-09-03

In [14]:
# save DFs
df1 = pd.DataFrame(callRows)
df2 = pd.DataFrame(speakerRows)

df1.to_csv(downloadDir / "DF1.csv", index=False)
df2.to_csv(downloadDir / "DF2.csv", index=False)

In [15]:
df1.head()

,EarningsCallID,CompanyName,CallDate,EarningsCallText
0,1,Fastenal,2026-10-14,Operator: Greetings. Welcome to Fastenal's 202...
1,2,BlackRock,2026-10-14,"Operator: Good morning. My name is Jen, and I ..."
2,3,Morgan Stanley,2026-10-14,Operator: Thank you for joining the Morgan Sta...
3,4,Sono-Tek,2026-10-14,"Operator: Good day, everyone, and welcome to t..."
4,5,ASML,2026-10-14,"Operator: Good day, and thank you for standing..."

In [16]:
df2.head()

,SpeakerTurnID,EarningsCallID,SpeakerName,PreparedOrQA,Text
0,1,1,Operator,Prepared,Greetings. Welcome to Fastenal's 2026 Third Qu...
1,2,1,Dray Schreiber,Prepared,Welcome to the Fastenal Company 2026 Third Qua...
2,3,1,Jeffery Watts,Prepared,"Thank you, Dray. Good morning, everyone, and w..."
3,4,1,Max Tunnicliff,Prepared,"Thank you, Jeff, and good morning, everyone. O..."
4,5,1,Jeffery Watts,Prepared,"Thanks, Max. Before we open the line, I think ..."

In [17]:
print("Calls:", len(df1))
print("Speaker turns:", len(df2))

Calls: 200
Speaker turns: 8796

In [18]:
# Different Q&A introductions require inspection.
if needsReview:
  print("Q&A boundary not detected; review these calls:")
  for callID, url in needsReview:
    print(callID, url)

Q&A boundary not detected; review these calls:
17 https://www.fool.com/earnings/call-transcripts/2026/10/13/leifras-lfs-q2-2026-earnings-call-transcript/
20 https://www.fool.com/earnings/call-transcripts/2026/10/09/oil-dri-odc-q4-2026-earnings-call-transcript/
23 https://www.fool.com/earnings/call-transcripts/2026/10/08/novagold-ng-q3-2026-earnings-call-transcript/
40 https://www.fool.com/earnings/call-transcripts/2026/10/02/yiren-digital-yrd-q2-2026-earnings-call-transcript/
53 https://www.fool.com/earnings/call-transcripts/2026/09/30/moving-image-mitq-q4-2026-earnings-call-transcript/
74 https://www.fool.com/earnings/call-transcripts/2026/09/24/atlasclear-atch-q4-2026-earnings-call-transcript/
77 https://www.fool.com/earnings/call-transcripts/2026/09/24/paychex-payx-q1-2027-earnings-call-transcript/
92 https://www.fool.com/earnings/call-transcripts/2026/09/16/ispire-ispr-q4-2026-earnings-call-transcript/
96 https://www.fool.com/earnings/call-transcripts/2026/09/15/51talk-coe-q2-2026-earnings-call-transcript/
97 https://www.fool.com/earnings/call-transcripts/2026/09/15/rent-the-runway-rent-q2-2026-earnings-call-transcript/
98 https://www.fool.com/earnings/call-transcripts/2026/09/15/abat-q4-2026-earnings-call-transcript/
99 https://www.fool.com/earnings/call-transcripts/2026/09/15/bioceres-biox-q4-2026-earnings-call-transcript/
104 https://www.fool.com/earnings/call-transcripts/2026/09/14/hain-celestial-hain-q1-2027-earnings-call-transcript/
107 https://www.fool.com/earnings/call-transcripts/2026/09/14/coinshares-cshr-q2-2026-earnings-call-transcript/
110 https://www.fool.com/earnings/call-transcripts/2026/09/11/moneyhero-mny-q2-2026-earnings-call-transcript/
116 https://www.fool.com/earnings/call-transcripts/2026/09/11/champions-oncology-csbr-q1-2027-earnings-call-transcript/
157 https://www.fool.com/earnings/call-transcripts/2026/09/09/optical-cable-occ-q3-2026-earnings-call-transcript/
167 https://www.fool.com/earnings/call-transcripts/2026/09/09/17-education-yq-q2-2026-earnings-call-transcript/
171 https://www.fool.com/earnings/call-transcripts/2026/09/09/us-global-investors-grow-q4-2026-earnings-call-transcript/
191 https://www.fool.com/earnings/call-transcripts/2026/09/09/guidewire-gwre-q4-2026-earnings-call-transcript/
195 https://www.fool.com/earnings/call-transcripts/2026/09/09/amber-ambr-q2-2026-earnings-call-transcript/
196 https://www.fool.com/earnings/call-transcripts/2026/09/09/ciena-cien-q3-2026-earnings-call-transcript/

Per checking, among the 22 non-detected Q&A, six have no Q&A appearing in the published transcript, four have question period opening, but no audience questions follow. For the other 12, our rule is too narrow to catch them.